version: "3"
services:
  app:
    container_name: app
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - "db"
  db:
    image: "postgres:11"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: backend-api
